### ISSUE TITLE
A NICE Future In China

### ISSUE THREAD

**Issue by CalvinRui** [codectile/crappy-esp#17]
Can you complie this and update for me? It's a big market in China and can help you make more money,my eamil: 3306309192@qq.com

**Comment by Floraly** [comment]
yes of course! But my BE Bypass is not for big Market dude! Its for individuals who identifie themselfs to make sure its not AC staff! But I contact you! Making money is always fine :-D Who really pays $1.000 for a PUBG Cheat? My cheat would cost $1.899 per package and it need active internet connection to my Server. Any attempt to decipher it would lead into losing access and lifetime ban your identitiy from my service + sharing your personal identity with other cheat devs!

**Comment by Floraly** [comment]
Look your mail!

**Comment by CalvinRui** [comment]
Hi，get your mail and noted below you mentioned.You know China is a big market and of course I will help you make much money and I will be your agent in China if your cheat is really working.Before we start to cooperate,I have the following points that need your cfm:
1,you said your cheat will cost $1.899,then what is the time for $1.899? A month?
2,you should make the cheat in Chinese,because which will be sold in Chinese users.
3,if you have finished the cheat,pls send me the cheat for testing firstly,if ok,then we can start to cooperate.

**Comment by Floraly** [comment]
The high numbers are the initial costs!
After that we need a monthly fee to fit our costs.
Our costs are actually covered by one customer who is one of the top players on PUBG.
We are really carefull with our products. Mostly no one of the candidates dont fullfill the identity process because they dont want to reveal their identity so we are not able to make business with anonymous people!
