### ISSUE TITLE
debug assertion failed

### ISSUE THREAD

**Issue by willerhehehe** [codectile/crappy-esp#18]
![error](https://user-images.githubusercontent.com/32084498/31803277-66110870-b585-11e7-94b1-854366270cb5.png)

**Comment by codectile** [comment]
compile in x64 and release mode

**Comment by Floraly** [comment]
I am using it and it works! If you don't know what Debug mode is. Just delete Game + Windows!
This method is detected on PUBG! Because it uses an Advanced BE Version which is activly maintained its like a Rootkit on your System.

To deal with BE kill the BE Service and then inject and see if things working in Debug mode.

Good luck dude!
